docker-compose:
    build: .
    net: "host"
    volumes:
        - /home/vagrant:/home/developer
        - .:/pwd
        - /var/run/docker.sock:/var/run/docker.sock
    stdin_open: true
    tty: true
    command: --file /pwd/testing-docker-compose.yml up 
