version: '2'
services:
    mongodb:
        image: mongo:latest
        expose:
        - "27017"

    foo:
        build: .
        depends_on:
        - mongodb
        links:
        - mongodb:mongodb
        ports:
        - "8080"
        environment:
            SPRING_DATA_MONGODB_HOST: mongodb
